export enum RouterEnum {
  INDEX = 'INDEX',
  PAGE = 'PAGE_INDEX',
  PAGE_TEMPLATE = 'PAGE_TEMPLATE',
  //
  SECURITY_USER = 'SECURITY_USER',
  SECURITY_GROUP = 'SECURITY_GROUP',
  //
  MODULE_QUIZ = 'MODULE_QUIZ',
  MODULE_QUIZ_CREATE = 'MODULE_QUIZ_CREATE',
  MODULE_QUIZ_UPDATE = 'MODULE_QUIZ_UPDATE',
  //
  MODULE_STEP = 'MODULE_STEP',
  MODULE_STEP_CREATE = 'MODULE_STEP_CREATE',
  MODULE_STEP_UPDATE = 'MODULE_STEP_UPDATE',
}
